wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688697663.401774
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 95
      3:
      - 23
      - 42
      4: 3.11.4
      5: 0.15.5
      6: 4.30.2
      8:
      - 5
